spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_springboot_courseapi?useTimezone=true&Timezone=UTC
    username: root
    password: Gui010203
  jpa:
    hibernate:
      ddl-auto: none
    #properties:
     # hibernate:
      #  dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false 
springdoc:
  swagger-ui:
    use-root-path: true
  paths-to-match: /api/**/v1/** 